import { TRENDS_BADGE_TYPES } from '../../../sharedComponents/trendsBadge';

export const spaceTypeEnergyData = [
    {
        id: '1',
        name: 'Mech. Room',
        value: 50,
        unit: 'kWh',
        consumption: 12553,
        percentage: 42,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '2',
        name: 'Pantry',
        value: 40,
        unit: 'kWh',
        consumption: 8553,
        percentage: 28,
        badgePercentage: 1,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '3',
        name: 'Other',
        value: 30,
        unit: 'kWh',
        consumption: 3503,
        percentage: 12,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '4',
        name: 'Kitchen',
        value: 20,
        unit: 'kWh',
        consumption: 533,
        percentage: 8,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.UPWARD_TREND,
    },
    {
        id: '5',
        name: 'Conference Room',
        value: 15,
        unit: 'kWh',
        consumption: 233,
        percentage: 5,
        badgePercentage: 1,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '6',
        name: 'Common Space',
        value: 10,
        unit: 'kWh',
        consumption: 63,
        percentage: 2,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.UPWARD_TREND,
    },
];

export const equipTypeEnergyData = [
    {
        id: '1',
        name: 'Cofee Machine',
        value: 50,
        unit: 'kWh',
        consumption: 12553,
        percentage: 42,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '2',
        name: 'Water Cooler',
        value: 40,
        unit: 'kWh',
        consumption: 8553,
        percentage: 28,
        badgePercentage: 1,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '3',
        name: 'Desktop PC',
        value: 30,
        unit: 'kWh',
        consumption: 3503,
        percentage: 12,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '4',
        name: 'Other',
        value: 20,
        unit: 'kWh',
        consumption: 533,
        percentage: 8,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.UPWARD_TREND,
    },
    {
        id: '5',
        name: 'Computer Monitor',
        value: 15,
        unit: 'kWh',
        consumption: 233,
        percentage: 5,
        badgePercentage: 1,
        badgeType: TRENDS_BADGE_TYPES.DOWNWARD_TREND,
    },
    {
        id: '6',
        name: 'Laptop',
        value: 10,
        unit: 'kWh',
        consumption: 63,
        percentage: 2,
        badgePercentage: 3,
        badgeType: TRENDS_BADGE_TYPES.UPWARD_TREND,
    },
];
