import React from 'react';

const initialNodes = [
    {
        id: 'horizontal-1',
        targetPosition: 'left',
        sourcePosition: 'right',
        type: 'breakerContainer',
        data: { label: 'Breaker 1' },
        position: { x: 250, y: 60 },
    },
    {
        id: 'horizontal-3',
        targetPosition: 'left',
        sourcePosition: 'right',
        type: 'breakerContainer',
        data: { label: 'Breaker 3' },
        position: { x: 250, y: 140 },
    },
    {
        id: 'horizontal-5',
        targetPosition: 'left',
        sourcePosition: 'right',
        type: 'breakerContainer',
        data: { label: 'Breaker 5' },
        position: { x: 250, y: 220 },
    },
    {
        id: 'horizontal-7',
        targetPosition: 'left',
        sourcePosition: 'right',
        type: 'breakerContainer',
        data: { label: 'Breaker 7' },
        position: { x: 250, y: 300 },
    },
    {
        id: 'horizontal-2',
        targetPosition: 'right',
        sourcePosition: 'left',
        data: { label: 'Breaker 2' },
        type: 'breakerContainer',
        position: { x: 700, y: 60 },
    },
    {
        id: 'horizontal-4',
        targetPosition: 'right',
        sourcePosition: 'left',
        data: { label: 'Breaker 4' },
        type: 'breakerContainer',
        position: { x: 700, y: 140 },
    },
    {
        id: 'horizontal-6',
        targetPosition: 'right',
        sourcePosition: 'left',
        data: { label: 'Breaker 6' },
        type: 'breakerContainer',
        position: { x: 700, y: 220 },
    },
    {
        id: 'horizontal-8',
        targetPosition: 'right',
        sourcePosition: 'left',
        data: { label: 'Breaker 8' },
        type: 'breakerContainer',
        position: { x: 700, y: 300 },
    },
    {
        id: 'horizontal-24',
        sourcePosition: 'left',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 1180, y: 120 },
    },
    {
        id: 'horizontal-46',
        sourcePosition: 'left',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 1180, y: 200 },
    },
    {
        id: 'horizontal-68',
        sourcePosition: 'left',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 1180, y: 280 },
    },
    {
        id: 'horizontal-13',
        sourcePosition: 'right',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 200, y: 120 },
    },
    {
        id: 'horizontal-35',
        sourcePosition: 'right',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 200, y: 200 },
    },
    {
        id: 'horizontal-57',
        sourcePosition: 'right',
        type: 'breakerLink',
        data: { label: 'Link' },
        position: { x: 200, y: 280 },
    },
];

export default initialNodes;
